baseURL="https://nhuquan.github.io"
languageCode="en-us"
title="Nhu Quan DANG"
theme = "nix"

[params]
  GithubID = "nhuquan"
  LinkedInID = "nhu-quan-dang-6208a162"
  Name = "Daniel Dang"
  HeaderUsername = "ddang"
  HeaderHostname = "home"
  Email = "quandangnhu@gmail.com"
  Mobile = "+84981682904"
  About = "Hi, I'm Daniel, senior software developer, and a simple man."
  ProfilePicture = "https://media.licdn.com/dms/image/C5603AQHwUUO3F7i7gQ/profile-displayphoto-shrink_200_200/0?e=1534377600&v=beta&t=W9DsGcOvyWMaJqm3zMR2W_wtcb0LekpEcxINWlgRz4Q"
  CvURL = ""

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
  [[menu.header]]
    name = "games"
    weight = 1
    url = "/games"
  [[menu.header]]
    name = "apps"
    weight = 2
    url = "/apps"
